### ISSUE TITLE
All the keys are bold after conversion

### ISSUE THREAD

**Issue by mosihe** [mwilliamson/python-mammoth#104] opened 2021-06-12 01:14 UTC
docx demo:
**YouTube** aaa
YouTube aaa
html :
**YouTube aaa
YouTube aaa**
I use Python 3.8.5 and Mammoth-1.4.16 on windows 10.

**Comment by mwilliamson** [comment] 2021-06-12 07:09
Could you provide a minimal example document, the actual HTML produced, and the expected HTML?

**Comment by mosihe** [comment] 2021-06-13 11:07
> Could you provide a minimal example document, the actual HTML produced, and the expected HTML?
ok.   And now I found something unusual.  
[test-demo.zip](https://github.com/mwilliamson/python-mammoth/files/6643764/test-demo.zip)
![image](https://user-images.githubusercontent.com/56816317/121804783-9f8fa600-cc7a-11eb-9b27-c6b48b8491fb.png)

**Comment by mwilliamson** [comment] 2021-06-14 06:35
It looks like you've applied the character style "Strong" to the second "YouTube", which Mammoth is converting to a `strong` tag. If you remove that character style, then you should see the HTML you expect.

**Comment by mwilliamson** [comment] 2021-06-20 19:15
Closing since it looks like Mammoth's working as intended.

**Closed by mwilliamson** 2021-06-20 19:15 UTC
