### ISSUE TITLE
How to convert one .docx contains a formulae to html ? It seems  that it is not supported? Can you give me another advice? thank you 

### ISSUE THREAD

**Issue by aslanxjc** [mwilliamson/python-mammoth#37] opened 2017-07-05 03:59 UTC
How to convert one .docx contains a formulae to html ? It seems  that it is not supported?
Can you give me another advice? thank you

**Comment by mwilliamson** [comment] 2017-07-09 13:24
Are you referring to Word's equation feature, or to formulas in tables? Neither is currently supported.

**Comment by mwilliamson** [comment] 2017-07-25 18:17
Assuming this is a request for equation support, this is a duplicate of #17.

**Closed by mwilliamson** 2017-07-25 18:17 UTC
