### ISSUE TITLE
mammoth.convert_to_html got an error

### ISSUE THREAD

**Issue by m358807551** [mwilliamson/python-mammoth#35] opened 2017-06-06 06:58 UTC
The codes:

`with open("test2.docx", "rb") as f:
        print mammoth.convert_to_html(f).value`

and the result:

Traceback (most recent call last):
  File "D:/myp/02_project/170601_test_mammoth/test_mammoth/main.py", line 15, in <module>
    main()
  File "D:/myp/02_project/170601_test_mammoth/test_mammoth/main.py", line 11, in main
    print mammoth.convert_to_html(f).value
  File "E:\python\lib\site-packages\mammoth\__init__.py", line 12, in convert_to_html
    return convert(*args, output_format="html", **kwargs)
  File "E:\python\lib\site-packages\mammoth\__init__.py", line 26, in convert
    return options.read_options(kwargs).bind(lambda convert_options:
  File "E:\python\lib\site-packages\mammoth\results.py", line 15, in bind
    result = func(self.value)
  File "E:\python\lib\site-packages\mammoth\__init__.py", line 27, in <lambda>
    docx.read(fileobj).map(transform_document).bind(lambda document:
  File "E:\python\lib\site-packages\mammoth\docx\__init__.py", line 26, in read
    ]).bind(lambda referents:
  File "E:\python\lib\site-packages\mammoth\results.py", line 15, in bind
    result = func(self.value)
  File "E:\python\lib\site-packages\mammoth\docx\__init__.py", line 27, in <lambda>
    _read_document(zip_file, body_readers, notes=referents[0], comments=referents[1])
  File "E:\python\lib\site-packages\mammoth\docx\__init__.py", line 59, in _read_document
    comments=comments,
  File "E:\python\lib\site-packages\mammoth\docx\document_xml.py", line 16, in read_document_xml_element
    return body_reader.read_all(body_element.children) \
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 42, in read_all
    result = self._read_all(elements)
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 474, in _read_xml_elements
    return _ReadResult.concat(lists.map(read, elements))
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 469, in read
    return handler(element)
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 120, in paragraph
    _read_xml_elements(element.children),
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 474, in _read_xml_elements
    return _ReadResult.concat(lists.map(read, elements))
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 469, in read
    return handler(element)
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 93, in run
    _read_xml_elements(element.children).map(add_complex_field_hyperlink),
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 474, in _read_xml_elements
    return _ReadResult.concat(lists.map(read, elements))
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 469, in read
    return handler(element)
  File "E:\python\lib\site-packages\mammoth\docx\body_xml.py", line 148, in read_fld_char
    complex_field_stack.pop()
IndexError: pop from empty list

**Comment by mwilliamson** [comment] 2017-06-06 10:08
Could you provide a minimal example document so that I can reproduce
the issue?

**Comment by mwilliamson** [comment] 2017-07-25 18:18
Closing since I'd need to look an example document to work out the problem. Feel free to reopen if you can provide one.

**Closed by mwilliamson** 2017-07-25 18:18 UTC

**Comment by sdhdez** [comment] 2020-10-01 17:22
Hi,

I have found a similar error after editing text content in existing files using `python-docx`. I've identified that the problem occurs after editing text in the bibliography of the document. A quick solution, for me, is avoiding the edition of paragraphs in the bibliography.

Sadly, I can't share my documents. At least, I hope my comment helps anyone having the same issue.

![image](https://user-images.githubusercontent.com/2230157/94816631-5d7c4800-03fc-11eb-97f2-60ccbbe8cf7a.png)

**Comment by urvisism** [comment] 2025-07-22 13:37
Hello @mwilliamson ,
I faced the same error "pop from empty list" while using mammoth.convert_to_html with my .docx file.
Here is my document to reproduce the error.

[AC TOITURE - LOT 2 - AE .docx](https://github.com/user-attachments/files/21368277/AC.TOITURE.-.LOT.2.-.AE.docx)
