### ISSUE TITLE
Any support for fonts?

### ISSUE THREAD

**Issue by dividor** [mwilliamson/python-mammoth#26] opened 2017-02-28 23:51 UTC
Hi There,

We love Mammoth! Absolutely great stuff.

We have some old legacy documents where the authors tended to use font (Courier new) to indicate code, rather than a code style. I know Mammoth isn't really designed to care about fonts, but by any chance is it possible to map finds to styles as with standard style mapping?

thanks a lot!

**Comment by mwilliamson** [comment] 2017-03-01 19:51
The [JavaScript implementation](https://github.com/mwilliamson/mammoth.js) supports document transforms, which allow you to modify the AST before it gets converted into HTML. In your case, it sounds like you'd want to check the font of each run and set the style of the paragraph accordingly. If it sounds like that might work for you, then it shouldn't be particularly tricky to implement, albeit with the same caveats i.e. that the representation of the AST may change between any release.

**Comment by dividor** [comment] 2017-03-01 20:51
Thanks for the reply. We're using Mammoth in Python, might it be possible with this version perhaps?

**Comment by mwilliamson** [comment] 2017-03-01 23:50
Yes, that's what I was suggesting: to implement document transforms in the Python implementation.

**Comment by dividor** [comment] 2017-03-07 21:47
Sounds like it might work for us, and understood about AST changing between releases.

Err, I'm being really dim here - but how can I modify ast please? Is there some documentation or code I an take a look at?

thanks a lot!

**Comment by mwilliamson** [comment] 2017-03-07 23:01
This is currently unimplemented in the Python implementation, so you can't do it at the moment.

**Comment by GitBruno** [comment] 2017-04-03 06:44
It is like you say, Mammoth deals with semantics only. However nothing stops us from prepping the documents before conversion.

I would use the find-change function:
    Find: Font: Courier
    Replace: Style: Courier

Which for example on the Mac you can automate using Automator:

- Get Specified Finder Items
- Open Word Documents
- Find and Replace Text in Word Documents
- Save Word Documents
- Close Word Documents

It would be cool to do stuff based on fonts but it seems out of scope for this tool.

Two option:
1. Close issue (out of scope)
2. Rewrite AST to reflect JavaScript branch

**Comment by mwilliamson** [comment] 2017-04-03 08:33
I'm not suggesting to rewrite the AST, but to expose the existing AST in the same way that the JavaScript implementation does so: that is, allowing a user to pass in a function that accepts a document and returns a document. So, for instance:

```python
def transform_paragraph(paragraph):
    runs = mammoth.transforms.get_descendants_of_type(paragraph, Run)
    if runs and all(run.font in _monospace_fonts for run in runs):
        return paragraph.copy(style_id="code", style_name="Code")
    else:
        return paragraph

convert_to_html(document_transform=mammoth.transforms.paragraphs(transform_paragraph))
```

**Comment by mwilliamson** [comment] 2017-04-03 10:54
I believe the below should now work on the latest commit on `master`. Could you give it a try and let me know?

```python
import mammoth.documents
import mammoth.transforms

_monospace_fonts = set(["Courier New"])

def transform_paragraph(paragraph):
    runs = mammoth.transforms.get_descendants_of_type(paragraph, mammoth.documents.Run)
    if runs and all(run.font in _monospace_fonts for run in runs):
        return paragraph.copy(style_id="code", style_name="Code")
    else:
        return paragraph

convert_to_html(transform_document=mammoth.transforms.paragraph(transform_paragraph))
```

**Comment by GitBruno** [comment] 2017-04-03 11:30
I received this error when trying to run latest version:

`AttributeError: 'module' object has no attribute 'copy'`

Have not checked properly, did it quickly, could be my install problem?

One thing I did notice, is that we need to add the usage info:

    usage: mammoth [-h] [--output-dir OUTPUT_DIR]
               [--output-format {markdown,html}] [--style-map STYLE_MAP]
               docx-path [output-path]

**Comment by mwilliamson** [comment] 2017-04-03 11:53
> I received this error when trying to run latest version with code above:
> 
> `AttributeError: 'module' object has no attribute 'copy'`
> 
> Have not checked properly, did it quickly, could be my install problem?

The dependencies have been updated, so you'll need to make sure you have them installed with the correct version. Specifically, cobble needs to be at 0.1.2. If that still doesn't work, then post a stack trace.

> One thing I did notice, is that we need to add the usage info:

Document transforms aren't supported by the CLI, so there's no usage info to add (for  the CLI). I was going to update the documentation once we make sure it actually works as intended.

**Comment by GitBruno** [comment] 2017-04-03 12:35
Thanks, that solved the issue!

Just tested and it's all working as expected.

Awesome work Michael!

**Comment by dividor** [comment] 2017-04-04 17:50
Hi mwilliamson,

Thanks ever so much for looking into this.

I cloned the latest version of python-mammoth and applied the changes you suggest above to my script. I see the transform_paragraph handler being called, but 'runs' doesn't seem to include information about font and so no mapping occurs.

I defined this ...

`# Function to convert Courier font to Code Style
def transform_paragraph(paragraph):
    _monospace_fonts = set(["Courier New"])
    runs = mammoth.transforms.get_descendants_of_type(paragraph, mammoth.documents.Run)
    print(runs)
    if runs and all(run.font in _monospace_fonts for run in runs):
        return paragraph.copy(style_id="code", style_name="Code")
    else:
        return paragraph`

Then calling mammoth with this ...

`result = mammoth.convert_to_html(docx_file,convert_image=convert_image,style_map=style_map,
                                         transform_document=mammoth.transforms.paragraph(transform_paragraph))`

I attach a test document.

thanks!

[Stuff.docx](https://github.com/mwilliamson/python-mammoth/files/894013/Stuff.docx)

**Comment by mwilliamson** [comment] 2017-04-04 18:42
As best as I can tell from your example, you want runs rather than paragraphs to be recognised as code i.e. you want inline code, not blocks of code. In which case, you'll need to do something more like:

```python

_monospace_fonts = set(["courier new"])

def transform_run(run):
    if run.font and run.font.lower() in _monospace_fonts:
        return run.copy(style_id="code", style_name="Code")
    else:
        return run

def _transform_runs(transform_run):
    def transform_element(element):
        if isinstance(element, mammoth.documents.Run):
            return transform_run(element)
        else:
            return element
    
    return _each_element(transform_element)

def _each_element(transform_element):
    def transform_element_and_children(element):
        if isinstance(element, mammoth.documents.HasChildren):
            children = list(map(transform_element, element.children))
            element = element.copy(children=children)
        
        return transform_element(element)
    
    return transform_element_and_children

transform_document = _transform_runs(transform_run)
```

**Comment by dividor** [comment] 2017-04-11 20:12
Thanks ever so much for the additional solution, I am indeed interested in converting inline text (we have a lot of configuration variables which use code format, but are courier font).

Unfortunately, in downloading the latest Mammoth and using this to call the code you kindly provided:

mammoth.convert_to_html(docx_file,convert_image=convert_image,style_map=style_map,
                                         transform_document=_transform_runs(transform_run))

Though I don't get any errors on running, I don't see to see courier font being converted to Code style.

Am I calling the code in an incorrect way perhaps?

thanks.

**Comment by mwilliamson** [comment] 2017-04-11 21:24
If you could provide an example document and a complete but minimal code example, then I can take a look when I get a chance.

**Comment by dividor** [comment] 2017-04-12 16:49
Thanks, please find attached sample doc.

I am using the code you provided above ...

`_monospace_fonts = set(["courier new"])

def transform_run(run):
    if run.font and run.font.lower() in _monospace_fonts:
        return run.copy(style_id="code", style_name="Code")
    else:
        return run

def _transform_runs(transform_run):
    def transform_element(element):
        if isinstance(element, mammoth.documents.Run):
            return transform_run(element)
        else:
            return element
    
    return _each_element(transform_element)

def _each_element(transform_element):
    def transform_element_and_children(element):
        if isinstance(element, mammoth.documents.HasChildren):
            children = list(map(transform_element, element.children))
            element = element.copy(children=children)
        
        return transform_element(element)
    
    return transform_element_and_children`

Then calling it with ...

`mammoth.convert_to_html(docx_file,convert_image=convert_image,style_map=style_map,
transform_document=_transform_runs(transform_run))`

[Stuff.docx](https://github.com/mwilliamson/python-mammoth/files/917278/Stuff.docx)

**Comment by mwilliamson** [comment] 2017-04-12 18:04
The recursion in `transform_element_and_children` needs fixing. The following code snippet works for me:

```python
import mammoth

_monospace_fonts = set(["courier new"])

def transform_run(run):
    print(run.font)
    if run.font and run.font.lower() in _monospace_fonts:
        return run.copy(style_id="code", style_name="Code")
    else:
        return run

def _transform_runs(transform_run):
    def transform_element(element):
        if isinstance(element, mammoth.documents.Run):
            return transform_run(element)
        else:
            return element
    
    return _each_element(transform_element)

def _each_element(transform_element):
    def transform_element_and_children(element):
        if isinstance(element, mammoth.documents.HasChildren):
            children = list(map(transform_element_and_children, element.children))
            element = element.copy(children=children)
        
        return transform_element(element)
    
    return transform_element_and_children

style_map = "r[style-name='Code'] => code"

with open("Stuff.docx", "rb") as fileobj:
    result = mammoth.convert_to_html(
        fileobj,
        style_map=style_map,
        transform_document=_transform_runs(transform_run),
    )
    print(result.value)
```

Those helper methods for transforming documents will be included in the next release, so there should be less code for you to write yourself.

**Comment by mwilliamson** [comment] 2017-04-16 16:03
In the latest version, you should be able to use:

```python
import mammoth

_monospace_fonts = set(["courier new"])

def transform_run(run):
    if run.font and run.font.lower() in _monospace_fonts:
        return run.copy(style_id="code", style_name="Code")
    else:
        return run

style_map = "r[style-name='Code'] => code"

with open("Stuff.docx", "rb") as fileobj:
    result = mammoth.convert_to_html(
        fileobj,
        style_map=style_map,
        transform_document=mammoth.transforms.run(transform_run),
    )
    print(result.value)
```

**Comment by dividor** [comment] 2017-04-18 17:09
Fantastic, works perfectly! Thanks ever so much, this is a hugely useful feature for us.

Sorry if this is a silly question, I tested by checking out from git, but when will this feature and [this feature](https://github.com/mwilliamson/mammoth.js/issues/36) be in the version I update with pip3 please?

thanks!

**Comment by mwilliamson** [comment] 2017-04-18 17:28
Glad to hear it works. This is already in the latest release.

**Closed by mwilliamson** 2017-04-18 17:28 UTC

**Comment by dividor** [comment] 2017-04-18 17:59
Great! Thanks again, great stuff.
